- name: docker build and push
  hosts: local  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t petstore .
      args:
        chdir: /var/lib/jenkins/workspace/myFirstJob

    - name: tag image
      command: docker tag petstore:latest ckharvi/petstore:latest 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://hub.docker.com/
        username: ckharvi
        password: LVpw2018@

    - name: Push image
      command: docker push ckharvi/petstore:latest

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 ckharvi/petstore:latest
